export const queryActions: any = {
  SET_QUERY_RESULT: 'SET_QUERY_RESULT',
  MERGE_MUTATION_RESPONSE: 'MERGE_MUTATION_RESPONSE',
  ROLLBACK_OPTIMISTIC_RESPONSE: 'ROLLBACK_OPTIMISTIC_RESPONSE',
  REMOVE_BACKUP_OPTIMISTIC_RESPONSE_DATA: 'REMOVE_BACKUP_OPTIMISTIC_RESPONSE_DATA',
};
